name: variable workflow
on: push

env:
  accessid: ${{ vars.ACCESS_ID }}

jobs:
  accessvars:
    runs-on: ubuntu-latest
    steps:
    - name: print var
      run: |
        echo $accessid
        echo ${{ secrets.ACCESS_SECRET }}
  
